# Generated by Django 4.2.4 on 2023-09-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='ph_namber',
            new_name='ph_number',
        ),
    ]
