# Generated by Django 4.2.4 on 2023-09-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_ph_namber_contacts_ph_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='ph_number',
            field=models.CharField(max_length=100, verbose_name='Телефоный номер'),
        ),
    ]
